pipe:
	gcc err_func.c pipe.c

sample:
	gcc err_func.c sample.c

popen:
	gcc err_func.c popen.c

read_command:
	gcc -o myuclc err_func.c to_lower_filter.c
	gcc err_func.c read_command.c

co_process:
	gcc -o add2 err_func.c add_2.c
	gcc err_func.c co_process.c
