t_execve:
	gcc -o envargs \
		-I../03_system_programming_concepts \
		-I../10_time \
		../10_time/curr_time.c \
		../03_system_programming_concepts/error_functions.c \
		../03_system_programming_concepts/get_num.c \
		envargs.c
	gcc  -I../03_system_programming_concepts \
		-I../10_time \
		../10_time/curr_time.c \
		../03_system_programming_concepts/error_functions.c \
		../03_system_programming_concepts/get_num.c \
		t_execve.c

