multi_wait:
	gcc -I../03_system_programming_concepts \
		-I../10_time \
		../10_time/curr_time.c \
		../03_system_programming_concepts/error_functions.c \
		../03_system_programming_concepts/get_num.c \
		multi_wait.c

print_wait_status:
	gcc -I../03_system_programming_concepts \
		-I../10_time \
		../10_time/curr_time.c \
		../03_system_programming_concepts/error_functions.c \
		../03_system_programming_concepts/get_num.c \
		print_wait_status.c


